[phases.setup]
nixPkgs = ["python311", "ffmpeg", "libGL", "libjpeg", "zlib", "pkg-config", "cmake"]

[phases.install]
cmds = [
  "python3.11 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn app:app"
