[phases.setup]
nixPkgs = ["python311", "ffmpeg", "libGL", "libjpeg", "zlib", "pkg-config", "cmake", "blas", "lapack"]

[phases.build]
cmds = []  # Prevent unwanted build commands like python app.py

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.start]
cmd = "/opt/venv/bin/gunicorn --bind 0.0.0.0:$PORT --log-level debug --access-logfile - --error-logfile - app:app"
